---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: stage
  labels:
    app: db
spec:
  ports:
    - name: db
      port: 5432
      targetPort: 5432
#  clusterIP: None
  selector:
    app: db
  type: ClusterIP
